"""Extensions GraphQL transport for the Python client.

Thin wrapper around httpx that lets facade clients (e.g. LedgerClient)
execute queries against the /extensions/graphql endpoint without pulling
in a dedicated GraphQL library. Responses are validated into the typed
Pydantic models generated by ariadne-codegen in ``graphql/generated/``
from the query documents in ``graphql/operations/``.

This is an implementation detail — consumers only interact with the
facade clients, which hide the transport entirely.
"""

from robosystems_client.graphql.client import GraphQLClient, GraphQLError

__all__ = ["GraphQLClient", "GraphQLError"]
