query GetLedgerEntity($entityId: String) {
  entity(entityId: $entityId) {
    id
    name
    legalName
    uri
    cik
    ticker
    exchange
    sic
    sicDescription
    category
    stateOfIncorporation
    fiscalYearEnd
    taxId
    lei
    industry
    entityType
    reportingStyleId
    phone
    website
    status
    isParent
    parentEntityId
    ownershipPct
    source
    sourceId
    sourceGraphId
    connectionId
    addressLine1
    addressCity
    addressState
    addressPostalCode
    addressCountry
    createdAt
    updatedAt
  }
}
